### ISSUE TITLE
installation ; signed driver required

### ISSUE THREAD

**Issue by t4-ravenbird** [Maxhy/dokany#1]
Tried to install but get err-message ;
http://postimg.org/image/e3corqb8b/

Also when I check the installation file-date of dokan.sys seems to be old?
http://postimg.org/image/id3f08n3x/

Nice initiative!

**Comment by Maxhy** [comment]
Mh some issue with the driver code signing certificate from GoDaddy. You will have to wait few more days sorry :\

**Comment by Maxhy** [comment]
Ok I updated the installation package with fixed signed drivers. Could you redownload the release and try again? Thanks.

**Comment by t4-ravenbird** [comment]
Yes, installs cleanly now.
(I notice size of download changed surprisingly much ; http://postimg.org/image/f0jamjqfz/ - dont know if that is expected)

**Comment by Maxhy** [comment]
Ok great :)
Yes this is excepted, it's coming from the intermediate certificates embedded when signing.
