### ISSUE TITLE
Place for DokanY discussion rather than "issues"?

### ISSUE THREAD

**Issue by TonyGravagno** [Maxhy/dokany#16]
I've been watching the progress of FUSE over Windows for years, and was sad when it seemed like Dokan had died on the vine. Thanks to everyone who has participated in it's renovation, and especially for this fork.

Once in a while I have questions about the software but would rather not clutter this Git Issue Tracker with them. Is there a forum somewhere or other location where people are discussing it? Thanks!

**Comment by Maxhy** [comment]
For me the best place for discussion is still the original Dokan Google Groups https://groups.google.com/forum/#!forum/dokan
Even if the captain left the boat it doesn't mean we can't drive it ;)

**Comment by TonyGravagno** [comment]
I posted a note there and hope to continue discussions. Thanks!
https://groups.google.com/d/msg/dokan/bVog4vz9Rzo/rFWowBNULFwJ
