### ISSUE TITLE
dokan.sys install failed in WS 2008 R2 x64

### ISSUE THREAD

**Issue by superhq** [Maxhy/dokany#3]
I compiled dokan in vs 2013 (wdk 8.1), and signed it, but dokan.sys driver install failed always.

**Comment by Maxhy** [comment]
Is this the same behavior with the provided release? https://github.com/Maxhy/dokany/releases

**Comment by superhq** [comment]
Yes, I try the provided release,  and install failed also. 
1. install DokanInstall_0.7.0.exe
2. dokanctl /r a
3. dokanctl /i a

The result:
-------------------------------------
C:\Program Files (x86)\Dokan\DokanLibrary>dokanctl.exe /i a
mounter path C:\Program Files (x86)\Dokan\DokanLibrary\mounter.exe
driver path C:\Windows\system32\drivers\dokan.sys
driver install failedmounter install ok
-------------------------------------

**Comment by superhq** [comment]
Sorry. I install  DokanInstall_0.7.0.exe success. but use <dokanctrl /r a>  and then <dokanctrl /i a>  is failed.
And my compiled version is failed always.

**Comment by Liryna** [comment]
I cannot reproduce the error, can you try to give some debug information if possible ?

**Comment by superhq** [comment]
Ｉ install *DokanInstall_0.7.0.exe* and then use:
**dokanctl /r a** to remove all server.
restart windows, and then:
**dokanctl /i a**
success. I think  when we remove dokan service, the service is only marked for delete,and we need reboot windows for delete it completely.

But my own compile version still install failed.
I put *dokan.sys* into  the **C:\windows\system32\driver** folder, and *dokan.dll* into the **C:\windows\syswow64** folder, and then use: **dokanctl /i a**. The result is：
*Service  (Dokan) installed
failed to start service (Dokan): 127
Service (Dokan) start failed
driver install failed*
... ...

(I set g_UserStdErr=TRUE.)
I have disabled windows driver signature when start windows, and I also try to use signing certificates to sign it, but failed all.

erron 127 is means:**ERROR_PROC_NOT_FOUND**:*The specified procedure could not be found.*. I don't know how to fix it.

**Comment by Maxhy** [comment]
I tried on a similar machine and I cannot reproduce your issue, I believe this is a local issue (we don't do more on our side excepting the signing process).
Try to clean all temporary file, get latest commits and rebuild the solution.

**Comment by superhq** [comment]
dokan.sys can install in WS 2008 now. I misused the build environments.  **win7 Release** is the right configure for WS 2008.
Thank you for all your help.
