### ISSUE TITLE
How to sign a Windows 64-bit driver

### ISSUE THREAD

**Issue by silvadenisaraujo** [Maxhy/dokany#8]
Hello Maxhy,

Sorry my lack of knowledge, I am starting at driver development. Would you mind to give me a brief explanation about, How you can sign a driver to work properly at Windows 64 bits enviroment ? Is there any company that does it for free ?

Thanks in advance.

**Comment by Maxhy** [comment]
You simply need a valid certificate for that (cost $$$), and then sign the file in command line (for instance https://github.com/Maxhy/dokany/blob/master/sign.bat is the script we use to sign drivers in dokany, but we cannot provide the certificate unfortunately).
I know ReactOS did it a few time for open source projects but I'm not sure they are still doing that (or it could takes weeks I believe, better to be sure about your release ;)).

Hope it heps.

**Comment by silvadenisaraujo** [comment]
Thank you very much, it was very helpful !
